version: '2'

services:

  elasticsearch:
    image: 'elasticsearch:6.5.1'
    container_name: kafka_elastic_search
    hostname: elasticsearch
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - kafka
  kibana:
    image: 'kibana:6.5.1'
    container_name: kafka_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/


  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
        - ./twitter-stream-final/target/scala-2.11:/tmp/app
    tty: true

  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  kafka:
      image: spotify/kafka
      networks: 
        - data-stream
      environment: 
        - KAFKA=localhost:9092
        - ZOOKEEPER=localhost:2181
      links:
        - spark-master
      expose:
       - '2181'
       - '9092'

networks: 
  data-stream:
    driver: bridge
